### ISSUE TITLE
Slider widget not updating slider position

### ISSUE THREAD

**Issue by glyg** [tonysyu/skloupe#1]
Running edgedetector_demo.py, I have some issues with the slider window not updating the slider position. This also happens when I run  example/widgets/slider_demo.py (I'll open an issue on the github page).

The bug is the same if I run:

```
# python example/widgets/slider_demo.py # from the shell
```

or

```
> run example/widgets/slider_demo.py # from ipython --plyab
```

I am using the GTKAgg backend.

**Comment by tonysyu** [comment]
Hmm, I've tested it on macosx, tkagg, and qt4agg backends, and I can't seem to reproduce any issues. Do you have access to one of these backends (just to check the consistency)?

Also, what do you mean when you say it's not updating? Is it grabbing the slider handle and then letting go when you still have the mouse pressed? Or does it not even grab the handle when you click?

Also, does the original [Matplotlib slider demo](http://matplotlib.sourceforge.net/examples/widgets/slider_demo.html) work for you?

**Comment by glyg** [comment]
It's not grabbing the slider at all. The values are changing though. 
I get the same effect with QT4Agg as a backend.

This is not happening on the original slider demo.

**Comment by tonysyu** [comment]
When you say the values are changing, are both the text and the plot changing?

If so it may be [an old issue](http://www.mail-archive.com/matplotlib-users@lists.sourceforge.net/msg14789.html) with Matplotlib. What version are you on?

**Comment by glyg** [comment]
The plot changes i.e.  the result of cany contour changes and is updated in the ImageViewer instance.  I'm running:

 [~]|22> pylab.**version**
    <22> '1.5.1'
 [~]|23> matplotlib.**version**
    <23> '1.0.1'

**Comment by tonysyu** [comment]
I _think_ I've figured out the bug here, and let me just say, that was a _really_ annoying bug.

Before Matplotlib 1.1, widgets were old-style classes (i.e, don't derive from `object`). As a consequence, Python properties aren't respected, so `value` was just a normal attribute, and the setter method defined for `value` was not getting called.

Could you test the [MPL 1.0 compatibility branch](https://github.com/tonysyu/skloupe/tree/mpl-1.0-compatibility). It uses multiple inheritance to solve the problem---which I'm not so thrilled about---but I couldn't think of a better solution (other than not using properties, which I'm also not thrilled about).

**Comment by glyg** [comment]
Bingo,
The mpl1 compatibility branch works fine.
